### PR TITLE
Fix detection of Flatpak JetBrains apps

### PR DESCRIPTION
**Pull request by alex1701c**
See https://github.com/alex1701c/JetBrainsRunner/issues/27

### CODE REVIEW

**Comment by alex1701c** [comment]
@DanielNoga Can you confirm this works for you?

**Comment by DanielNoga** [comment]
Thanks for fast response!

I can confirm, that IDEA is found with this branch. But Webstorm not. It is another issue, should I create separate report?

**Comment by alex1701c** [comment]
Yes, please do so

**Comment by DanielNoga** [comment]
Thank, I created it https://github.com/alex1701c/JetBrainsRunner/issues/28

**Pull request merged**
